# Generated by Django 5.0.3 on 2024-05-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
